Enhance trying out the language page
One-Language/Document pull request #51
Opened 2021-08-27 00:05 UTC by jbampton

Run pre-commit

2021-08-27 00:32 UTC, johnbampton submitted a review, later dismissed

2021-08-28 07:39 UTC, amir-shiati approved these changes

2021-08-28 07:50 UTC, pedramcvx1 requested changes
other than that, LGTM.

2021-08-28 07:50 UTC, pedramcvx1 commented on en/trying-out-the-language.md
> -For this case, you first need to install One compiler, currently, You are able to compile the One compiler in Linux (both x86_64 and i386 architecture) and macOS, and BSD family, and finally Windows
For this case, you first need to install One compiler. **Currently you** are able to compile the One compiler **on** Linux (both x86_64 and i386 architecture), **macOS, the BSD family, and finally Windows OS.**

2021-08-29 04:54 UTC, jbampton commented on en/trying-out-the-language.md
> +For this case, you first need to install the One compiler. You are able to compile the One compiler in Linux (both x86_64 and i386 architecture) and macOS, the BSD family, and finally Windows OS.
```suggestion
For this case, you first need to install the One compiler. You are able to compile the One compiler in Linux (both x86_64 and i386 architecture), macOS, the BSD family, and finally Windows OS.
```

2021-08-30 14:08 UTC, johnbampton approved these changes

2021-08-30 14:26 UTC, pedramcvx1 approved these changes
LGTM

2021-08-30 14:36 UTC, jbampton commented
Changed just now to one approving green review to merge.

2021-08-30 14:37 UTC, merged